# Generated by Django 4.1.1 on 2022-10-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsp_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='double_run_institution_woodin',
            old_name='time_stamp',
            new_name='time_stamp_curr',
        ),
    ]
