# Generated by Django 4.1.1 on 2022-10-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishing_pieces',
            name='Quality_of_labeling',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
